/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tuhnpk00528;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fpoly
 */
public class frmSanPham extends javax.swing.JFrame {

    /**
     * Creates new form frmSanPham
     */
    public frmSanPham() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblLoaiSanPham = new javax.swing.JTable();
        pnlFunction = new javax.swing.JPanel();
        lblMaSP = new javax.swing.JLabel();
        txtMaSP = new javax.swing.JTextField();
        lblTenSP = new javax.swing.JLabel();
        txtTenSP = new javax.swing.JTextField();
        lblMoTa = new javax.swing.JLabel();
        txtMoTa = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnTaoMoi = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        lblGia = new javax.swing.JLabel();
        lblSoLuong = new javax.swing.JLabel();
        lblMaLoai = new javax.swing.JLabel();
        txtGia = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        lblTimKiem = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        cbbmaloai = new javax.swing.JComboBox<>();
        lblFormTitle = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblThongTinSanPham = new javax.swing.JTable();

        tblLoaiSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "STT", "Mã loại", "Tên", "Mô tả"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblLoaiSanPham);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlFunction.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 102)));

        lblMaSP.setText("Mã sản phẩm");

        txtMaSP.setEditable(false);

        lblTenSP.setText("Tên Sản Phẩm");

        lblMoTa.setText("Mô tả");

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnTaoMoi.setText("Tạo mới");
        btnTaoMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoMoiActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        lblGia.setText("Giá");

        lblSoLuong.setText("Số Lượng");

        lblMaLoai.setText("Mã Loại");

        lblTimKiem.setText("Tìm Kiếm");

        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyReleased(evt);
            }
        });

        cbbmaloai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout pnlFunctionLayout = new javax.swing.GroupLayout(pnlFunction);
        pnlFunction.setLayout(pnlFunctionLayout);
        pnlFunctionLayout.setHorizontalGroup(
            pnlFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFunctionLayout.createSequentialGroup()
                .addGroup(pnlFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFunctionLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(pnlFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFunctionLayout.createSequentialGroup()
                                .addComponent(lblGia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFunctionLayout.createSequentialGroup()
                                .addComponent(lblMoTa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtMoTa, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFunctionLayout.createSequentialGroup()
                                .addComponent(lblTenSP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFunctionLayout.createSequentialGroup()
                                .addComponent(lblMaSP)
                                .addGap(43, 43, 43)
                                .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFunctionLayout.createSequentialGroup()
                                .addGroup(pnlFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSoLuong)
                                    .addComponent(lblMaLoai))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnlFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSoLuong, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                                    .addComponent(cbbmaloai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(pnlFunctionLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(btnThem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnXoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTaoMoi))
                    .addGroup(pnlFunctionLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(lblTimKiem)
                        .addGap(77, 77, 77)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        pnlFunctionLayout.setVerticalGroup(
            pnlFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFunctionLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnlFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaSP)
                    .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenSP)
                    .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMoTa)
                    .addComponent(txtMoTa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGia, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbmaloai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnXoa)
                    .addComponent(btnSua)
                    .addComponent(btnTaoMoi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(pnlFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTimKiem)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        lblFormTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFormTitle.setForeground(new java.awt.Color(255, 153, 51));
        lblFormTitle.setText("QUẢN LÝ SẢN PHẨM");

        tblThongTinSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã Sản Phẩm", "Tên", "Mô tả", "Giá", "Số Lượng", "Mã Loại"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblThongTinSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblThongTinSanPhamMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblThongTinSanPham);
        if (tblThongTinSanPham.getColumnModel().getColumnCount() > 0) {
            tblThongTinSanPham.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(lblFormTitle)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlFunction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblFormTitle)
                .addGap(18, 18, 18)
                .addComponent(pnlFunction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed

        String tenSP, moTa,Gia,SoLuong,maLoaiSP;
        tenSP = txtTenSP.getText();
        moTa = txtMoTa.getText();
        Gia = txtGia.getText();
        SoLuong = txtSoLuong.getText();
        //maLoai = cbbmaloai.getSelectedItem().toString();
        Object[] obj = cbbmaloai.getSelectedObjects();
        DisplayValueModel item = (DisplayValueModel) obj[0];
        maLoaiSP = item.DisplayValue.toString();
        
        String cautruyvan = "insert into SanPham(Ten,MoTa,Gia,SoLuong,MaLoai) "
        + "values(N'"+tenSP+"',N'"+moTa+"',"+Gia+","+SoLuong+","+maLoaiSP+")" ;
        if(!tenSP.equals("")&& !moTa.equals("") && !Gia.equals("") &&!SoLuong.equals("") &&!maLoaiSP.equals("") ){
            BaiTapBuoi1.connection.ExcuteQueryUpdateDB(cautruyvan);
        }else{
            System.out.println("Bạn Chưa Nhập Dữ liệu");
        }
        LayDuLieu();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        String maSP,tenSP,moTa,Gia,SoLuong,maLoaiSP;
        maSP = txtMaSP.getText();
        tenSP = txtTenSP.getText();
        moTa = txtMoTa.getText();
        Gia = txtGia.getText();
        SoLuong = txtSoLuong.getText();
        maLoaiSP = cbbmaloai.getSelectedObjects()[0].toString();
        
        
        String cautruyvan = "update SanPham "
        + "set Ten = N'" + tenSP + "', MoTa=N'"+moTa+"',Gia="+Gia+",SoLuong="+SoLuong+",MaLoai="+maLoaiSP+""
        + " where MaSP = "+maSP;
        BaiTapBuoi1.connection.ExcuteQueryUpdateDB(cautruyvan);
        LayDuLieu();

    }//GEN-LAST:event_btnSuaActionPerformed

    private void tblThongTinSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblThongTinSanPhamMouseClicked
        int viTriDongVuaBam = tblThongTinSanPham.getSelectedRow();
        txtMaSP.setText(tblThongTinSanPham.getValueAt(viTriDongVuaBam,1).toString());
        txtTenSP.setText(tblThongTinSanPham.getValueAt(viTriDongVuaBam,2).toString());
        txtMoTa.setText(tblThongTinSanPham.getValueAt(viTriDongVuaBam,3).toString());
        txtGia.setText(tblThongTinSanPham.getValueAt(viTriDongVuaBam,4).toString());
        txtSoLuong.setText(tblThongTinSanPham.getValueAt(viTriDongVuaBam,5).toString());
        //txtMaLoai.setText(tblThongTinSanPham.getValueAt(viTriDongVuaBam,6).toString());
        //cbbmaloai.setSelectedItem("Nhân Viên");
        String tenLoai= tblThongTinSanPham.getValueAt(viTriDongVuaBam, 6).toString();
        setSelectedCombobox(tenLoai);
    }//GEN-LAST:event_tblThongTinSanPhamMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        LayDuLieu();
        LayDuLieuLoaiSanPham();
        
    }//GEN-LAST:event_formWindowOpened
    private void LayDuLieuLoaiSanPham(){
        try {
            String cauTruyVan = "select * from LoaiSanPham";
            ResultSet rs = BaiTapBuoi1.connection.ExcuteQueryGetTable(cauTruyVan);
            DefaultComboBoxModel cbbModel = new DefaultComboBoxModel();
//            cbbModel.addElement("Phần tử 1");
//            cbbModel.addElement("Phần tử 2");
//            cbbModel.addElement("Phần tử 3");
//            cbbmaloai.setModel(cbbModel);
            while(rs.next()){
                System.out.println(rs.getInt("MaLoai"));
                System.out.println(rs.getString("Ten"));
                DisplayValueModel valueModel = new DisplayValueModel(rs.getString("Ten"), rs.getInt("MaLoai"));
                
//              cbbModel.addElement(rs.getString("Ten"));
                cbbModel.addElement(valueModel);
                
            }
            cbbmaloai.setModel(cbbModel);
        } catch (SQLException ex) {
            System.out.println(ex.toString());
            
        }
        
    } 
    private void txtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyReleased
        String TuKhoaTimKiem = txtTimKiem.getText();
        String cautruyvan = "select *from SanPham "
                + "where Ten like N'%"+TuKhoaTimKiem+"%'"+"or MoTa like N'%"+TuKhoaTimKiem+"%'";
        
        ResultSet rs = BaiTapBuoi1.connection.ExcuteQueryGetTable(cautruyvan);
        
        Object[] obj = new Object[] {"STT","Mã Sản Phẩm","Tên Sản Phẩm","Mô Tả","Giá","Số Lượng","Tên Loại"};
        DefaultTableModel tableModel = new DefaultTableModel(obj,0);
        tblThongTinSanPham.setModel(tableModel);
        
        
        try {
            while(rs.next()){
                Object[] item = new Object[7];  
                item[0]=tblThongTinSanPham.getRowCount() + 1;
                item[1]=rs.getInt("MaSP");
                item[2]=rs.getString("Ten");
                item[3]= rs.getString("MoTa");
                item[4]= rs.getString("Gia");
                item[5]= rs.getString("SoLuong");
//                item[6]= rs.getString("MaLoai");
                String maLoai= rs.getString("MaLoai");
                item[6]=GetTenLoaiDuaMaLoai(maLoai);
                tableModel.addRow(item);
//                System.out.println(rs.getInt("MaLoai"));
//                System.out.println(rs.getString("Ten"));
//                System.out.println(rs.getString("MoTa"));
            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_txtTimKiemKeyReleased

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int[] mangViTriDuocChon = tblThongTinSanPham.getSelectedRows();         
        for(int i = 0 ; i< mangViTriDuocChon.length ; i++ ){
           
           String maSPCanXoa = tblThongTinSanPham.getValueAt(mangViTriDuocChon[i],1).toString();           
           String cautruyvan = "delete from SanPham where MaSP = "+maSPCanXoa;            
           BaiTapBuoi1.connection.ExcuteQueryUpdateDB(cautruyvan);
        }
        LayDuLieu();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnTaoMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoMoiActionPerformed
        txtMaSP.setText("");
        txtTenSP.setText("");
        txtMoTa.setText("");
        txtGia.setText("");
        txtSoLuong.setText("");
        cbbmaloai.setSelectedIndex(0);
    }//GEN-LAST:event_btnTaoMoiActionPerformed
     private void LayDuLieu(){
        String cautruyvan = "select *from SanPham";
        ResultSet rs = BaiTapBuoi1.connection.ExcuteQueryGetTable(cautruyvan);
        
        Object[] obj = new Object[] {"STT","Mã Sản Phẩm","Tên Sản Phẩm","Mô Tả","Giá","Số Lượng","Tên Loại"};
        DefaultTableModel tableModel = new DefaultTableModel(obj,0);
        tblThongTinSanPham.setModel(tableModel);
        
        
        try {
            while(rs.next()){
                Object[] item = new Object[7];  
                item[0]=tblThongTinSanPham.getRowCount() + 1;
                item[1]=rs.getInt("MaSP");
                item[2]=rs.getString("Ten");
                item[3]= rs.getString("MoTa");
                item[4]= rs.getString("Gia");
                item[5]= rs.getString("SoLuong");
//                item[6]= rs.getString("MaLoai");
                String maLoai= rs.getString("MaLoai");
                item[6]=GetTenLoaiDuaMaLoai(maLoai);
                tableModel.addRow(item);
//                System.out.println(rs.getInt("MaLoai"));
//                System.out.println(rs.getString("Ten"));
//                System.out.println(rs.getString("MoTa"));
            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
    }
    private void setSelectedCombobox(String tenLoai){
        //Vòng lặp lấy tất cả Loại sản phẩm trong combobox
        for(int i=0;i<cbbmaloai.getItemCount();i++){
            //Lấy từng giá trị Elenment trong combobox và gán vào 1 biến Object
            //Vì combobox kiểu Object
            Object obj = cbbmaloai.getItemAt(i);
            //nếu Object khác null
            if(obj != null){
                //ép kiểu kiểu Objec về kiểu DisplyValueModel như mình đã định nghĩa
                DisplayValueModel m = (DisplayValueModel)obj;
                //nếu tên loại bằng vói DisplayMenber của Obj thì chọn lại combobox
                if(tenLoai.equals(m.DisplayMenber)){
                    //cbbmaloai.getSelctedIndex(i);//chọn lại combobox theo vị trí
                    
                    cbbmaloai.setSelectedItem(m);//chọn lại combobox theo element
                }
            }
        }
    } 
    //lay ten loai dua vao ma loai
    private String GetTenLoaiDuaMaLoai(String maLoai){
        String tenLoai = "";
        String cauTruyVan = "select Ten from LoaiSanPham where MaLoai = " + maLoai;
        ResultSet rs = BaiTapBuoi1.connection.ExcuteQueryGetTable(cauTruyVan);
        try {
            while(rs.next()){
                tenLoai = rs.getString("Ten");
            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
        return tenLoai; 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSanPham().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnTaoMoi;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbbmaloai;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblFormTitle;
    private javax.swing.JLabel lblGia;
    private javax.swing.JLabel lblMaLoai;
    private javax.swing.JLabel lblMaSP;
    private javax.swing.JLabel lblMoTa;
    private javax.swing.JLabel lblSoLuong;
    private javax.swing.JLabel lblTenSP;
    private javax.swing.JLabel lblTimKiem;
    private javax.swing.JPanel pnlFunction;
    private javax.swing.JTable tblLoaiSanPham;
    private javax.swing.JTable tblThongTinSanPham;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtMaSP;
    private javax.swing.JTextField txtMoTa;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenSP;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
